import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const cases = [
  {
    title: 'ПОВУЗАМ',
    slug: 'povuzam',
    category: 'Платформы',
    badge: 'ПЛАТФОРМА',
    description: 'Платформа для абитуриентов: вузы, направления, заявки.',
    metric: 'Федеральный охват',
    url: 'https://povuzam.ru',
    color: 'from-violet-100 to-blue-100',
    coverImage: '/assets/cases/povuzam.jpg',
    isActive: true,
    isFeatured: true,
    sortOrder: 1,
  },
  {
    title: 'BatNorton',
    slug: 'batnorton',
    category: 'E-commerce',
    badge: 'E-COMMERCE',
    description: 'Интернет-магазин с каталогом, фильтрами, корзиной и оплатой.',
    metric: '10 лет данных перенесено',
    url: 'https://batnorton.com',
    color: 'from-slate-100 to-zinc-200',
    coverImage: '/assets/cases/batnorton.jpg',
    isActive: true,
    isFeatured: true,
    sortOrder: 2,
  },
  {
    title: 'DA.MOTORS',
    slug: 'damotors',
    category: 'Telegram',
    badge: 'TELEGRAM MINI APP',
    description: 'Каталог автомобилей в Telegram с заявками и ботом.',
    metric: '+40% конверсия',
    url: null,
    color: 'from-sky-100 to-blue-200',
    coverImage: '/assets/cases/damotors.jpg',
    isActive: true,
    isFeatured: true,
    sortOrder: 3,
  },
  {
    title: 'AI-агент для автоматизации',
    slug: 'ai-contracts',
    category: 'AI',
    badge: 'AI',
    description: 'Анализ договоров и выжимка ключевых условий за секунды',
    metric: '3 мин — время ответа',
    url: null,
    color: 'from-indigo-100 to-violet-100',
    coverImage: null,
    isActive: true,
    isFeatured: true,
    sortOrder: 4,
  },
  {
    title: 'AVANGARD31',
    slug: 'avangard31',
    category: 'Сайты',
    badge: 'CRM',
    description: 'Система недвижимости: сайт, CRM, Telegram-бот, парсер объектов.',
    metric: 'Комплексная digital-система',
    url: null,
    color: 'from-blue-100 to-cyan-100',
    coverImage: null,
    isActive: true,
    isFeatured: false,
    sortOrder: 5,
  },
  {
    title: 'Bella Hasias',
    slug: 'bella-hasias',
    category: 'Telegram',
    badge: 'SAAS',
    description: 'Премиальная Telegram-экосистема с AI-ассистентом и подпиской.',
    metric: 'Подписочная модель',
    url: null,
    color: 'from-rose-100 to-pink-50',
    coverImage: null,
    isActive: true,
    isFeatured: false,
    sortOrder: 6,
  },
  {
    title: 'AI-помощник для Авито',
    slug: 'ai-avito',
    category: 'AI',
    badge: 'AI',
    description: 'Автоматизировали обработку входящих запросов.',
    metric: '80% запросов без менеджера',
    url: null,
    color: 'from-indigo-100 to-blue-100',
    coverImage: null,
    isActive: true,
    isFeatured: false,
    sortOrder: 7,
  },
  {
    title: 'Платформа AI-агентов',
    slug: 'ai-platform',
    category: 'AI',
    badge: 'AI SAAS',
    description: 'Voice + Video AI ассистенты для бизнеса в реальном времени.',
    metric: 'Realtime AI агенты',
    url: null,
    color: 'from-violet-100 to-indigo-100',
    coverImage: null,
    isActive: true,
    isFeatured: false,
    sortOrder: 8,
  },
  {
    title: 'Свой Хлеб',
    slug: 'svoikhleb',
    category: 'Telegram',
    badge: 'TELEGRAM',
    description: 'Mini App для локального бизнеса: каталог, заявки, бот.',
    metric: 'Заявки через Telegram',
    url: null,
    color: 'from-amber-100 to-yellow-50',
    coverImage: null,
    isActive: true,
    isFeatured: false,
    sortOrder: 9,
  },
  {
    title: 'AI видео для бизнеса',
    slug: 'ai-video-business',
    category: 'Видео',
    badge: 'ВИДЕО',
    description: 'Reels, Shorts, TikTok с AI-генерацией: сценарии, монтаж, субтитры.',
    metric: 'Рекламные ролики с AI',
    url: null,
    color: 'from-rose-100 to-orange-100',
    coverImage: null,
    isActive: true,
    isFeatured: false,
    sortOrder: 10,
  },
];

async function main() {
  for (const c of cases) {
    const result = await prisma.case.upsert({
      where: { slug: c.slug },
      update: c,
      create: c,
    });
    console.log('✓', result.id, result.title);
  }
  console.log(`\nSeeded ${cases.length} cases.`);
  await prisma.$disconnect();
}

main().catch(e => { console.error(e); prisma.$disconnect(); process.exit(1); });
